project:
  type: website
  output-dir: docs
  
website:
  title: "Arildo Dias"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - cv.qmd
      - publications.qmd
      - research.qmd
      - blog.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/arildodias/mywebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Arildo Dias"

format:
  html:
    theme: cerulean
    toc: true

editor: source

