---
title: "Publications"
---


You can find my full list of publications on my [Google Scholar profile](https://scholar.google.com.br/citations?user=TZE1QnQAAAAJ&hl=pt-BR).

## Selected Publications

1. [Climbing mechanisms as a central trait to understand the ecology of lianas across the tropics](https://onlinelibrary.wiley.com/doi/full/10.1111/geb.13846)
   *Arildo Dias*, Rafael S. Oliveira, Fernando R. Martins, Frans Bongers, Niels P. R. Anten, Frank J. Sterck. Global Ecology and Biogeography (2024)

2. [Using essential biodiversity variables to assess forest ecosystem integrity](https://www.frontiersin.org/articles/10.3389/ffgc.2023.1098901/full)
   *Arildo Dias*, Shaya Van Houd, Katrin Meschin, ..., Donalda Karnauskaite. Frontiers in Forests and Global Change (2023)

3. [Priorities for synthesis research in ecology and environmental science](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.4342)
   Benjamin S. Halpern, Carl Boettiger, Michael C. Dietze, ..., *Arildo Dias*,...,Casey Youngflesh. Ecosphere (2023)

4. [Global maps of soil temperature](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.16060)
   Jonas J. Lembrechts, Johan van den Hoogen, Juha Aalto,..., *Arildo Dias*,..., Jonathan Lenoir. Global Change Biology (2021)



