---
title: "Research"
---

# My Research


My research is centered at the interface of biodiversity (taxonomic, functional, and phylogenetic), ecosystem services, and the conservation and sustainable use of natural resources. I have used various analytical and theoretical approaches combining empirical datasets with remote sensing and modeling to assess how climate change and land use influence species distribution, functional biodiversity, and ecosystem functioning. Besides trying to answer fundamental scientific questions, I am also particularly interested in translate this knowledge to support public policies and business applications while, at the same time, increasing societal benefits fairly and equitably. For instance, questions that I have explored include: what biodiversity and ecosystem metrics can support the assessment and monitoring of Nature-based Solutions (NbSs) by providing a more holistic perspective that not only carbon-centered metrics as currently is done in most of the voluntary carbon markets? what is the potential of green technologies (e.g., Web 3.0, machine learning, remote sensing, and IoT sensors) to provide data mobilization and transparency to support consistent allocation of financial resources to forest conservation?  

